name: nose_stamp
description: A new Flutter project.

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  rename: ^3.0.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.2.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  http: ^0.13.5
  path: ^1.8.3
  mime: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/naver_logo.png
    - assets/images/kakao_logo.png
    - assets/images/google_logo.png
    - assets/images/


dev_dependencies:
  flutter_lints: ^3.0.1  # 또는 최신 버전
