spring.sql.init.mode=always
spring.jmx.enabled=true
spring.application.name=pet_noseprint_id_service
spring.datasource.url=jdbc:mysql://localhost:3306/PetAppDB
spring.datasource.username=root
spring.datasource.password=1254163
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jwt.access-secret=parkSongEunparkSongEunparkSongEunparkSongEun
spring.jwt.refresh-secret=parkGoEunparkGoEunparkGoEunparkGoEunparkGoEun
spring.data.redis.host=localhost
spring.data.redis.port=6379

kakao.client_id = bfe85662415fa27df288f85a2fd42b47
kakao.redirect_uri = http://localhost:8080/users/oauth/kakao/callback

spring.security.oauth2.client.registration.google.client-id=68958539271-rfdq11n1jrjulo58gmjij437khadrdoq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect_uri= http://localhost:8080/users/oauth/google/callback
spring.security.oauth2.client.registration.google.scope=profile,email

naver.client_id = nre8DpI9n9PtZyFtVb9u
naver.client_secret =krvzSf2M8R
naver.redirect_uri = http://localhost:8080/users/oauth/naver/callback


spring.profiles.include=oauth