spring.sql.init.mode=always
spring.jmx.enabled=true
spring.application.name=pet_noseprint_id_service
spring.datasource.url=jdbc:mysql://localhost:3306/PetAppDB
spring.datasource.username=root
spring.datasource.password=1254163
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jwt.access-secret=parkSongEunparkSongEunparkSongEunparkSongEun
spring.jwt.refresh-secret=parkGoEunparkGoEunparkGoEunparkGoEunparkGoEun
spring.data.redis.host=localhost
spring.data.redis.port=6379